### ISSUE TITLE
Error in output: 'static' mode

### ISSUE THREAD

**Issue by Antonytm** [exdst/jss-astro-public#35]
## Steps to reproduce

* Open `astro.config.mjs` file
* Change `output` mode to `static`: `output: 'static'`
* Run `npm run build`

### Expected result

Build should provide completely static output

### Actual result

Build fails with error 

```
10:57:05   └─ /api/editing/page/index.htmlSyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at specConsumeBody (node:internal/deps/undici/undici:5306:9)
    at _Request.json (node:internal/deps/undici/undici:5196:18)
    at file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/dist/server/pages/api/editing/page.astro.mjs?time=1730883423677:10:37
    at page (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/dist/server/chunks/astro/server_D0jJqQcg.mjs:402:12)
    at callComponentAsTemplateResultOrResponse (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/node_modules/astro/dist/runtime/server/render/astro/render.js:90:31)   
    at renderToAsyncIterable (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/node_modules/astro/dist/runtime/server/render/astro/render.js:132:32)
    at renderPage (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/node_modules/astro/dist/runtime/server/render/page.js:31:30)
    at lastNext (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/node_modules/astro/dist/core/render-context.js:151:31)
Unexpected end of JSON input
  Stack trace:
    at JSON.parse (<anonymous>)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at _Request.json (node:internal/deps/undici/undici:5196:18)
    at page (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/dist/server/chunks/astro/server_D0jJqQcg.mjs:402:12)
    at renderToAsyncIterable (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/node_modules/astro/dist/runtime/server/render/astro/render.js:132:32)
    at lastNext (file:///C:/source/jss-astro-public/astro-sitecore-jss/packages/astro-sitecore-jss-sample/node_modules/astro/dist/core/render-context.js:151:31)
ERROR: "astro:build" exited with 1.
```

**Comment by Antonytm** [comment]
## Temporarily workaround:

* Rename `page.astro` to `page.astro_`
* Rename `render.astro` to `render.astro_`
